export const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
const avg=a=>a.length?a.reduce((s,n)=>s+n,0)/a.length:0;
function trend(p,w=20){const a=p.slice(-w);if(a.length<8)return{direccion:"LATERAL",fuerza:0,cambioPorcentual:0,lateral:true};const first=avg(a.slice(0,Math.ceil(a.length/3))),last=avg(a.slice(-Math.ceil(a.length/3)));const c=first?((last-first)/first)*100:0;const f=Math.min(3,Math.abs(c)*900);return{direccion:Math.abs(c)<.003?"LATERAL":c>0?"ALCISTA":"BAJISTA",fuerza:f,cambioPorcentual:c,lateral:Math.abs(c)<.003}}
function rsi(p,period=14){if(p.length<period+1)return null;let g=0,l=0;const a=p.slice(-(period+1));for(let i=1;i<a.length;i++){const d=a[i]-a[i-1];d>0?g+=d:l-=d}if(!l)return 100;const rs=(g/period)/(l/period);return 100-100/(1+rs)}
function momentum(p,w=10){if(p.length<w+1)return{direccion:"NEUTRAL",fuerza:0,porcentaje:0};const a=p[p.length-w-1],b=p.at(-1),pc=a?((b-a)/a)*100:0;return{direccion:Math.abs(pc)<.001?"NEUTRAL":pc>0?"POSITIVO":"NEGATIVO",fuerza:Math.min(3,Math.abs(pc)*1200),porcentaje:pc}}
function flow(p,w){const a=p.slice(-(w+1));let up=0,down=0;for(let i=1;i<a.length;i++){if(a[i]>a[i-1])up++;else if(a[i]<a[i-1])down++}const diff=Math.abs(up-down),tot=Math.max(1,up+down);return{direccion:diff/tot<.16?"NEUTRAL":up>down?"ALCISTA":"BAJISTA",fuerza:Math.min(3,diff/2),subidas:up,bajadas:down}}
function volatility(p,w=30){const a=p.slice(-w);if(a.length<5)return{nivel:"BAJA",porcentaje:0};const m=avg(a),sd=Math.sqrt(avg(a.map(x=>(x-m)**2))),pc=m?(sd/m)*100:0;return{nivel:pc>.08?"MUY ALTA":pc>.04?"ALTA":pc>.015?"MEDIA":"BAJA",porcentaje:pc}}
function lateral(t,m,f){return{lateral:t.lateral||m.direccion==="NEUTRAL"||f.direccion==="NEUTRAL"}}
function fib(p,w=80){const a=p.slice(-w);if(a.length<25)return{disponible:false};const high=Math.max(...a),low=Math.min(...a),range=high-low,current=a.at(-1);if(!range)return{disponible:false};const levels=[23.6,38.2,50,61.8,78.6].map(pc=>({porcentaje:pc,precio:high-range*(pc/100),distanciaPorcentual:Math.abs(current-(high-range*(pc/100)))/range*100}));levels.sort((x,y)=>x.distanciaPorcentual-y.distanciaPorcentual);const near=levels[0];return{disponible:true,estado:near.distanciaPorcentual<4?"NEAR LEVEL":"ACTIVE",cercaDeNivel:near.distanciaPorcentual<4,nivelCercano:near,maximo:high,minimo:low,direccionBase:a.at(-1)>=a[0]?"ALCISTA":"BAJISTA",tipoZona:a.at(-1)>=a[0]?"Possible support":"Possible resistance"}}
function digitStats(d){const a=d.slice(-80),count=a.length,freq=Array(10).fill(0);a.forEach(x=>Number.isInteger(x)&&freq[x]++);const even=a.filter(x=>x%2===0).length,low=a.filter(x=>x<=4).length;let hot=0;freq.forEach((n,i)=>{if(n>freq[hot])hot=i});return{cantidad:count,pares:even,impares:count-even,porcentajePares:count?even/count*100:0,porcentajeImpares:count?(count-even)/count*100:0,bajos:low,altos:count-low,porcentajeBajos:count?low/count*100:0,porcentajeAltos:count?(count-low)/count*100:0,digitoCaliente:hot,frecuenciaCaliente:freq[hot]}}
export function crearResumenTecnico({precios=[],digitos=[],modo="fast"}={}){const t=trend(precios,modo==="complete"?35:20),r=rsi(precios),m=momentum(precios,modo==="complete"?18:10),fc=flow(precios,8),fm=flow(precios,20),v=volatility(precios);return{modo,tendencia:t,rsi:r,interpretacionRsi:{zona:r==null?"SIN DATOS":r>68?"ALTA":r<32?"BAJA":"NEUTRAL",direccion:r==null?"NEUTRAL":r>55?"BULLISH":r<45?"BEARISH":"NEUTRAL",fuerza:r==null?0:Math.min(3,Math.abs(r-50)/10)},momentum:m,flujoCorto:fc,flujoMedio:fm,volatilidad:v,mercadoLateral:lateral(t,m,fc),fibonacci:fib(precios),estadisticasDigitos:digitStats(digitos)}}
export function resumenTecnicoValido(r){return Boolean(r&&r.tendencia&&r.momentum&&r.flujoCorto&&r.volatilidad)}
export const limitarNumero=clamp;
